sudo: required
language: node_js
node_js:
- node
install:
- npm install
addons:
  sonarcloud:
    organization: carlsonorozco-github
    token:
      secure: m1JN0SJTm1M9nnByFpsynwa3xcaC5ybQDPKSKFXHMjK31TM5CXyA/SpK5E/8vFzEtPUfCTPDdmM2cmGKzIr0xh3CGURotBTYlJ2jV5f/VReHWcoBPry7wB6jzHdFlQ2pnAK6zDyRSJEo5JRoVPJ8CS8SYDX4GBDRBd20bgdO+AVga0KySGveKU378lR6QYlroM6jK31rF04M/SNw6Nzja7LocY/mDb5BILd5v/ZTZBik0xB8DivTVq3dE++Wy1sJD6PnUSreeJXl/p/Mqlz7AzhSkW7tLIaOG65+r7L1ExyJVpKnuwjW3+BdMAofma0pW+pfo9JU1eyIzBr4VkaJ0hVN/QsJFKh0mPlryin24Xa9k5/ZBvuAWJEBNamA9LXwITWOiYhDA+gZUf+Etm4EPoggmB95bbiGMvCznOO37/cgXekYsY1/NoKeMfPEAEB1kBMy9UZ0zVp7tiuuQcjp4oPxeC6BT7ONNaBddUb3lnhme45oBCp/z1LBVz1Z3qvngozatHY661WTXAIn1IqJzgIZneoIQikQLiWbdwg6DXeJAyatLA5AMvKw13Kcr/9kymqG88Z/XAhX4Xeee6UysLMiNRmg/pK6C430sZgBylbDUa+6lrq4RPpgaPKohHrX97MWntgOUFfqt87AGWyMTGyh77/iW10ZNwXEjG+hFZk=
    github_token:
      secure: SxlrNXa+aoWBMraNUz7PVfo1u+Ha7kEPOIBMCKJknyqCqIaciRSnFIBFZApk+tun+5G5jNsL7g7xIsOm3/V5bePP2TMHMloMHBXAat/9SV1/9I+Lbn5B4pue43ghbbMWeeYHpd9rNan0dplgldSuJhNtLjfwcuGwIwqkvQl9ZWkrSbFT/GS6xJNBPZcO4ovFUQDyzAx7YbpR7q55zWlCpzLLWOllgzKqrqmePGfeAQ/5DMgfgaSSlSUS/TwvawSfEd1aY2ro4tdnBXXffEZU6+82S2fBSTiDKduHz6G/1dEBF8NTO3PdQjfi3TdnfxM4TkITanir7YEU9x29NpYhcOsUF2ndoDmqrUf7x+CedevoTGpXIoUKqeCr2uUXVG0w29c5IZITMwUVUSLVbibZ7yx7nKmsVa4ZRAii0uuch+tNAIEi3h4CohoS6mZGyu/M7mc5TfWG+pcdvNvCJYOdsT1fhNeLHKPv9zTKPgtKaFYeWsmeWkiqur3Tyc3TdH2hRMCph17Yj16674VP7f6GOzkxYoyb5TES0uMyEyf4YWw58j0GnUMJXUJ2yHbG5My3Hy+RN6wNHr3nBXcJ7OOu98ZHeSpSaXXCkFrNU8HK3fQESgcRrR3VO0zcCa1Q3O+FAAzpOG8OrVTYxnNw8v1SpnGIuBiUPn6fPeRPTMUD9+Y=
    branches:
    - master
    - develop
script:
- npm test
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
    secure: Uy1F6fAl0JKs3B67zY8vOJX+f8wVxbDxtVkafUJtvXmDM5CqXbqltx8gZA5oz3mRT1mWhQFcavIf6QiCUS6gB4dISXiZ2HtoIXiATDb6j9KzvcTMxzLBmSYkLz9h6QvoijwvNhavxc5MKp1lHaaN6MRExs+WKIKYPcADfGujyyqSksle1II/FRko5wSkELIK5ZLzGf20SzHUkhsqsubk6lylqRvagcap2Md0lK6tVEvFWKPAmIoBlYt/lhaUBWOskeknQOLdkD4CJ8ZKxvYetTSkslsX30iyFoSbvDzx8ePi8i9/I4bUml1VmT/tfBZwV6VE3LLO9cLYqMc4CjC88sfyXJOKSB5sZyZ4+e7NhgciYzUXlPBqBYE4pcqopEnWWvxy/1xAmHgHv7tJanD1cvvyWVXV205F1InSM2nO8COJ8EgHBOf9FxaHCcmNhJXZiARJT1aCutxTpSAQ8nW2D8G40S4h+72oanTCDQN4aNR5MODU5B1WeZw7xw3Ok4Qtv7N0wA5ayylBKbSaIS4sGmG526jd7IapG0HayBRQBhWsTAwqnOxmyPtmyWIVotiUlVF+knjy8vw/mjmzAj+0w48jnJoEaKEU3sarqb8XsE31YjjnESpFhp7m8BtOdEWRS72eQHA0K6XyRzAKeC9NSbiaUbr2g/TsIkzk3nyhHHI=
