sudo: required
language: node_js
node_js:
- node
install:
- npm install
addons:
  sonarcloud:
    organization: carlsonorozco-github
    token:
      secure: m1JN0SJTm1M9nnByFpsynwa3xcaC5ybQDPKSKFXHMjK31TM5CXyA/SpK5E/8vFzEtPUfCTPDdmM2cmGKzIr0xh3CGURotBTYlJ2jV5f/VReHWcoBPry7wB6jzHdFlQ2pnAK6zDyRSJEo5JRoVPJ8CS8SYDX4GBDRBd20bgdO+AVga0KySGveKU378lR6QYlroM6jK31rF04M/SNw6Nzja7LocY/mDb5BILd5v/ZTZBik0xB8DivTVq3dE++Wy1sJD6PnUSreeJXl/p/Mqlz7AzhSkW7tLIaOG65+r7L1ExyJVpKnuwjW3+BdMAofma0pW+pfo9JU1eyIzBr4VkaJ0hVN/QsJFKh0mPlryin24Xa9k5/ZBvuAWJEBNamA9LXwITWOiYhDA+gZUf+Etm4EPoggmB95bbiGMvCznOO37/cgXekYsY1/NoKeMfPEAEB1kBMy9UZ0zVp7tiuuQcjp4oPxeC6BT7ONNaBddUb3lnhme45oBCp/z1LBVz1Z3qvngozatHY661WTXAIn1IqJzgIZneoIQikQLiWbdwg6DXeJAyatLA5AMvKw13Kcr/9kymqG88Z/XAhX4Xeee6UysLMiNRmg/pK6C430sZgBylbDUa+6lrq4RPpgaPKohHrX97MWntgOUFfqt87AGWyMTGyh77/iW10ZNwXEjG+hFZk=
    github_token:
      secure: SxlrNXa+aoWBMraNUz7PVfo1u+Ha7kEPOIBMCKJknyqCqIaciRSnFIBFZApk+tun+5G5jNsL7g7xIsOm3/V5bePP2TMHMloMHBXAat/9SV1/9I+Lbn5B4pue43ghbbMWeeYHpd9rNan0dplgldSuJhNtLjfwcuGwIwqkvQl9ZWkrSbFT/GS6xJNBPZcO4ovFUQDyzAx7YbpR7q55zWlCpzLLWOllgzKqrqmePGfeAQ/5DMgfgaSSlSUS/TwvawSfEd1aY2ro4tdnBXXffEZU6+82S2fBSTiDKduHz6G/1dEBF8NTO3PdQjfi3TdnfxM4TkITanir7YEU9x29NpYhcOsUF2ndoDmqrUf7x+CedevoTGpXIoUKqeCr2uUXVG0w29c5IZITMwUVUSLVbibZ7yx7nKmsVa4ZRAii0uuch+tNAIEi3h4CohoS6mZGyu/M7mc5TfWG+pcdvNvCJYOdsT1fhNeLHKPv9zTKPgtKaFYeWsmeWkiqur3Tyc3TdH2hRMCph17Yj16674VP7f6GOzkxYoyb5TES0uMyEyf4YWw58j0GnUMJXUJ2yHbG5My3Hy+RN6wNHr3nBXcJ7OOu98ZHeSpSaXXCkFrNU8HK3fQESgcRrR3VO0zcCa1Q3O+FAAzpOG8OrVTYxnNw8v1SpnGIuBiUPn6fPeRPTMUD9+Y=
    branches:
    - master
    - develop
script:
- npm test
- sonar-scanner
cache:
  directories:
  - $HOME/.sonar/cache
env:
  matrix:
    secure: qAAl9eDEMyGZ6qdZq61z3pHySzBO5D0zcI3hXoZe8suHYyv5cDo1rsdvl8mpH77BIJgm2+u8UTW39VDmHL7/ZoUVC6FypagzP/EOBoUuj3guE6dETmM7Py9Dr+goxh5H5vqhmQRz6LQCnJog5bw+oC6yxm/aBNnsnsuxod1znP0d7oKr9kNPfCj/wWLOp/86kpmisyFJt89PnTvqK07DN0JeEC3yJj0WessIQ2aZvUyCxj9dfiWXBmj9O+pQiZHpfAg2YzY01UMkpQ0/N0eVkUb93odkXwOSnXypj97s9AjMu6RUSWjhdhiVQ30AfusjlU6i1tuuKDfl/Z3eFBbPxLLrxbJ7Vga7arrWPqeas0yRm92fsT0oA1xF1QwECYbbpm/iwqd/NFW3Vbk4c4pcOIQihs+YJzAMhYYXb8UdFB0RbliDRgFnA5fRB5cxZIyogYpmE3OmfOo4dfvSImfkOZ5MGTazLuvJmVcimPXBdGILL7NemS5VVZG76brV/Ea5I9KdknZ5AB38zvtiz8EQpXiuVQarZjZRB5yshxGVoA3Lc8/X909Gi0k6xckAksFxjURI5PxN6cJ7i7zKtmRIjTl+Fbl2UssBq/VOLKJH8syAf9YAmMO3qy2rIa5Ff3GfmY51lWd0FY9AldLR4Zxi8m2RPWH96YJ4IOL7li61uZU=
